services:
  - type: web
    name: telegram-bot-vip
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
      value: mongodb+srv://teste:SfePlug@tesye.qazpla.mongodb.net/?retryWrites=true&w=majority&appName=Tesye
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true